# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - age18gvherf08ux7p9wphej4ek66qdjwsrcdtsxdcvuyj8pd9vtw2czspjzqqz
          - age18up687pggfu99c9k9zkc23gvsdsqwq4hjp97mvx0ltnm5th5qdxsmrsp7e
          - age1x8yaptq72fax5sgpm7tndtcezj72dsj4lmm0zvyrhn7nxmqd7fnqkrj9mu
          - age1s4nwygp3uquwlfxlzgvqyuq4d639sv2pfasphm2y2cwjqktz73rqmukvu3
          - age1gqmac05eldm7pcq0nx88394hyuc7u0d4nth0kl4xgp35va5zu4rqts6fxv
          - age1qlwm8kh9esraq0qej7dd63c6su3zrdkq6xxztn3hx6yulqz5d93qeh3c6k
          - age10kwuy3nwqfduuq2q0a62hhf3ghpe0r2j430ctt6z4w6f3jm9vfdqlhvf9x
