# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  services.power-profiles-daemon.enable = true;

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usb_storage"
        "sd_mod"
        "amdgpu"
      ];
      kernelModules = [ ];
      systemd.enable = true;
      luks.devices = {
        "cryptroot".device = "/dev/disk/by-uuid/be7af1e7-2193-4ff7-91f5-90b9690a1ca3";
        "cryptswap".device = "/dev/disk/by-uuid/b9af0d1a-1e8a-4768-bd11-6c9495549e5f";
      };
    };
    extraModulePackages = [ ];
    loader = {
      efi.canTouchEfiVariables = true;
      timeout = lib.mkDefault 0;
      systemd-boot = {
        extraInstallCommands = ''
          echo "default @saved" > /boot/loader/loader.conf
        '';
        configurationLimit = 2;
        enable = lib.mkForce false;
        editor = false;
      };
    };
    lanzaboote = {
      enable = true;
      pkiBundle = "/etc/secureboot";
      measuredBoot = {
        enable = true;
        pcrs = [
          0
          1
          2
          3
          4
          7
        ];
        pcrlockPolicy = "/var/lib/systemd/pcrlock/pcrlock.json";
        pcrlockDirectory = "/var/lib/pcrlock.d";
      };
    };
  };

  fileSystems = {
    "/home/alex/Documents/Programming" = {
      device = "/dev/disk/by-uuid/4bcd078c-f295-4626-a80f-f77d42347411";
      fsType = "btrfs";
      options = [ "subvol=@Programming" ];
    };
    "/home/alex/Documents/Programming/.snapshots" = {
      device = "/dev/disk/by-uuid/4bcd078c-f295-4626-a80f-f77d42347411";
      fsType = "btrfs";
      options = [ "subvol=@Programming/.snapshots" ];
    };
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "defaults"
        "size=8G"
        "mode=755"
      ];
    };
    "/home" = {
      device = "/dev/disk/by-uuid/4bcd078c-f295-4626-a80f-f77d42347411";
      fsType = "btrfs";
      options = [ "subvol=@nixhome" ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/740C-0338";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/4bcd078c-f295-4626-a80f-f77d42347411";
      fsType = "btrfs";
      options = [ "subvol=@nixtmpfsnix" ];
      neededForBoot = true;
    };
  };

  swapDevices = [ { device = "/dev/mapper/cryptswap"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
