{
  lib,
  config,
  pkgs,
  uiSettings ? { },
  ...
}:

let
  lua = lib.generators.mkLuaInline;
  stripFirst = s: builtins.substring 1 (builtins.stringLength s - 1) s;
  hyprlandMonitors = uiSettings.hyprlandMonitors or [ ",preferred,auto,auto" ];
  colorValue =
    name:
    let
      key = stripFirst name;
    in
    "rgb("
    + stripFirst (
      if lib.hasAttr key config.pywal-nix.colourScheme.colours then
        config.pywal-nix.colourScheme.colours.${key}
      else
        config.pywal-nix.colourScheme.special.${key}
    )
    + ")";
  parseMonitor =
    monitor:
    let
      parts = lib.splitString "," monitor;
      part =
        index: fallback: if builtins.length parts > index then builtins.elemAt parts index else fallback;
    in
    {
      output = part 0 "";
      mode = part 1 "preferred";
      position = part 2 "auto";
      scale = part 3 "auto";
    };
  bind = keys: dispatcher: {
    _args = [
      (lua keys)
      (lua dispatcher)
    ];
  };
  bindWithFlags = keys: dispatcher: flags: {
    _args = [
      (lua keys)
      (lua dispatcher)
      flags
    ];
  };
  exec = command: "hl.dsp.exec_cmd(${builtins.toJSON command})";
  execLine = command: "  hl.exec_cmd(${builtins.toJSON command})\n";
in
lib.mkIf (uiSettings.graphical or false) {
  home.activation.removeAutogeneratedHyprlandConf = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    hyprland_conf="$HOME/.config/hypr/hyprland.conf"
    if [ -f "$hyprland_conf" ] \
      && grep -q "This config is a STUB" "$hyprland_conf" \
      && grep -q "autogenerated = 1" "$hyprland_conf"; then
      rm "$hyprland_conf"
    fi
  '';

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "lua";
    settings = {
      mainMod._var = "SUPER";
      zenWorkspace._var = "1";
      terminalWorkspace._var = "2";
      codeWorkspace._var = "3";
      obsidianWorkspace._var = "4";

      config = {
        general = {
          gaps_in = 5;
          gaps_out = 15;
          border_size = 3;
          col = {
            active_border = {
              colors = [
                (colorValue "$color1")
                (colorValue "$color1")
                (colorValue "$color2")
              ];
              angle = 45;
            };
            inactive_border = {
              colors = [
                (colorValue "$color3")
                (colorValue "$color3")
                (colorValue "$color4")
              ];
              angle = 45;
            };
          };
          resize_on_border = true;
          allow_tearing = false;
          layout = "scrolling";
        };
        scrolling = {
          wrap_focus = true;
        };
        decoration = {
          rounding = 10;
          active_opacity = 1.0;
          inactive_opacity = 0.8;
          blur = {
            enabled = true;
            size = 2;
            passes = 1;
            special = true;
            vibrancy = 0.1696;
          };
        };
        animations.enabled = true;
        misc = {
          force_default_wallpaper = 1;
          disable_hyprland_logo = true;
        };
        input = {
          kb_layout = "us";
          follow_mouse = 1;
          sensitivity = 0;
          touchpad = {
            natural_scroll = true;
            disable_while_typing = false;
          };
        };
        xwayland.force_zero_scaling = true;
      };

      curve._args = [
        "myBezier"
        {
          type = "bezier";
          points = [
            [
              0.05
              0.9
            ]
            [
              0.1
              1.05
            ]
          ];
        }
      ];
      animation = [
        {
          _args = [
            {
              leaf = "windows";
              enabled = true;
              speed = 7;
              bezier = "myBezier";
            }
          ];
        }
        {
          _args = [
            {
              leaf = "windowsOut";
              enabled = true;
              speed = 7;
              bezier = "default";
              style = "popin 80%";
            }
          ];
        }
        {
          _args = [
            {
              leaf = "border";
              enabled = true;
              speed = 10;
              bezier = "default";
            }
          ];
        }
        {
          _args = [
            {
              leaf = "borderangle";
              enabled = true;
              speed = 8;
              bezier = "default";
            }
          ];
        }
        {
          _args = [
            {
              leaf = "fade";
              enabled = true;
              speed = 7;
              bezier = "default";
            }
          ];
        }
        {
          _args = [
            {
              leaf = "workspaces";
              enabled = true;
              speed = 10;
              bezier = "myBezier";
              style = "slide";
            }
          ];
        }
        {
          _args = [
            {
              leaf = "specialWorkspace";
              enabled = true;
              speed = 6;
              bezier = "myBezier";
              style = "slidefadevert -80";
            }
          ];
        }
      ];
      gesture = {
        fingers = 4;
        direction = "horizontal";
        action = "workspace";
      };
      device = [
        {
          name = "frmw0004:00-32ac:0006-consumer-control-1";
          natural_scroll = true;
        }
        {
          name = "thinkpad-essential-wireless-mouse";
          sensitivity = -1.0;
        }
        {
          name = "logitech-usb-receiver";
          sensitivity = -0.75;
        }
      ];
      monitor = map parseMonitor hyprlandMonitors;
      env = [
        {
          _args = [
            "XCURSOR_SIZE"
            "24"
          ];
        }
        {
          _args = [
            "HYPRCURSOR_SIZE"
            "24"
          ];
        }
        {
          _args = [
            "ELECTRON_OZONE_PLATFORM_HINT"
            "wayland"
          ];
        }
        {
          _args = [
            "QT_QPA_PLATFORMTHEME"
            "qt6ct"
          ];
        }
        {
          _args = [
            "GOPATH"
            (lua ''os.getenv("HOME") .. "/go"'')
          ];
        }
        {
          _args = [
            "GOBIN"
            (lua ''os.getenv("HOME") .. "/go/bin"'')
          ];
        }
        {
          _args = [
            "YARNBIN"
            (lua ''os.getenv("HOME") .. "/.yarn/bin"'')
          ];
        }
        {
          _args = [
            "PYENV_ROOT"
            (lua ''os.getenv("HOME") .. "/.pyenv"'')
          ];
        }
        {
          _args = [
            "PATH"
            (lua ''os.getenv("HOME") .. "/.pyenv/bin:" .. os.getenv("PATH") .. ":" .. os.getenv("HOME") .. "/go/bin:" .. os.getenv("HOME") .. "/.yarn/bin:" .. os.getenv("HOME") .. "/.local/bin:" .. os.getenv("HOME") .. "/.rvm/bin"'')
          ];
        }
        {
          _args = [
            "XDG_CONFIG_HOME"
            (lua ''os.getenv("HOME") .. "/.config"'')
          ];
        }
        {
          _args = [
            "XDG_DATA_HOME"
            (lua ''os.getenv("HOME") .. "/.local/share"'')
          ];
        }
        {
          _args = [
            "HYPRSHOT_DIR"
            (lua ''os.getenv("HOME") .. "/Screenshots"'')
          ];
        }
      ];
      on._args = [
        "hyprland.start"
        (lua ''
          function()
          ${execLine "/usr/lib/polkit-kde-authentication-agent-1"}${execLine "hyprsunset"}${execLine "dunst"}${execLine "quickshell --config topbar"}${execLine "xremap $HOME/.config/xremap/config.yml"}${execLine "sleep 1 && wl-copy-slurp"}  hl.exec_cmd("zen-beta", { workspace = zenWorkspace .. " silent" })
            hl.exec_cmd("alacritty", { workspace = terminalWorkspace .. " silent" })
            hl.exec_cmd("code", { workspace = codeWorkspace .. " silent" })
            hl.exec_cmd("obsidian", { workspace = obsidianWorkspace .. " silent" })
          end
        '')
      ];

      bind = [
        (bind ''mainMod .. " + RETURN"'' (exec "alacritty"))
        (bind ''mainMod .. " + C"'' "hl.dsp.window.close()")
        (bind ''mainMod .. " + L"'' (exec "hyprlock"))
        (bind ''mainMod .. " + J"'' ''hl.dsp.window.float({ action = "toggle" })'')
        (bind ''mainMod .. " + space"'' (exec "pidof gorg || gorg -a"))
        (bind ''mainMod .. " + grave"'' (exec ''sh -c 'dunstify "Start and size" "$(slurp)"''))
        (bind ''mainMod .. " + left"'' ''hl.dsp.focus({ direction = "left" })'')
        (bind ''mainMod .. " + right"'' ''hl.dsp.focus({ direction = "right" })'')
        (bind ''mainMod .. " + up"'' ''hl.dsp.focus({ direction = "up" })'')
        (bind ''mainMod .. " + down"'' ''hl.dsp.focus({ direction = "down" })'')
        (bind ''mainMod .. " + Tab"'' "hl.dsp.focus({ workspace = zenWorkspace })")
        (bind ''mainMod .. " + q"'' "hl.dsp.focus({ workspace = terminalWorkspace })")
        (bind ''mainMod .. " + w"'' "hl.dsp.focus({ workspace = codeWorkspace })")
        (bind ''mainMod .. " + e"'' "hl.dsp.focus({ workspace = obsidianWorkspace })")
        (bind ''mainMod .. " + r"'' "hl.dsp.focus({ workspace = 5 })")
        (bind ''mainMod .. " + SHIFT + Tab"'' "hl.dsp.window.move({ workspace = zenWorkspace })")
        (bind ''mainMod .. " + SHIFT + q"'' "hl.dsp.window.move({ workspace = terminalWorkspace })")
        (bind ''mainMod .. " + SHIFT + w"'' "hl.dsp.window.move({ workspace = codeWorkspace })")
        (bind ''mainMod .. " + SHIFT + e"'' "hl.dsp.window.move({ workspace = obsidianWorkspace })")
        (bind ''mainMod .. " + SHIFT + r"'' "hl.dsp.window.move({ workspace = 5 })")
        (bind ''mainMod .. " + S"'' ''hl.dsp.workspace.toggle_special("magic")'')
        (bind ''mainMod .. " + SHIFT + S"'' ''hl.dsp.window.move({ workspace = "special:magic" })'')
        (bind ''mainMod .. " + mouse_down"'' ''hl.dsp.focus({ workspace = "e+1" })'')
        (bind ''mainMod .. " + mouse_up"'' ''hl.dsp.focus({ workspace = "e-1" })'')
        (bind ''"PRINT"'' (exec "hyprshot -m window -m active --clipboard-only"))
        (bind ''"SHIFT + PRINT"'' (exec "hyprshot -m region --clipboard-only"))
        (bind ''mainMod .. " + H"'' (exec "dunstctl close"))
        (bind ''mainMod .. " + SHIFT + H"'' (exec "dunstctl history-pop"))
        (bind ''mainMod .. " + V"'' (exec "wl-copy-picker gorg -m equation,dmenu"))
        (bind ''mainMod .. " + G"'' "hl.dsp.group.toggle()")
        (bind ''mainMod .. " + N"'' "hl.dsp.group.next()")
        (bind ''mainMod .. " + SHIFT + N"'' "hl.dsp.group.prev()")
        (bind ''mainMod .. " + B"'' (exec "$HOME/.local/bin/btcon"))
        (bind ''mainMod .. " + F"'' "hl.dsp.window.fullscreen()")
        (bindWithFlags ''mainMod .. " + mouse:272"'' "hl.dsp.window.drag()" { mouse = true; })
        (bindWithFlags ''mainMod .. " + mouse:273"'' "hl.dsp.window.resize()" { mouse = true; })
        (bindWithFlags ''"XF86AudioRaiseVolume"'' (exec "pamixer -i 5") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"XF86AudioLowerVolume"'' (exec "pamixer -d 5") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"XF86AudioMute"'' (exec "pamixer -t") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"XF86MonBrightnessUp"'' (exec "brightnessctl s 10%+") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"XF86MonBrightnessDown"'' (exec "brightnessctl s 10%-") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"SHIFT + XF86MonBrightnessUp"'' (exec "hyprctl hyprsunset identity") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"SHIFT + XF86MonBrightnessDown"'' (exec "hyprctl hyprsunset temperature 1000") {
          locked = true;
          repeating = true;
        })
        (bindWithFlags ''"XF86AudioNext"'' (exec "playerctl next") { locked = true; })
        (bindWithFlags ''"XF86AudioPause"'' (exec "playerctl play-pause") { locked = true; })
        (bindWithFlags ''"XF86AudioPlay"'' (exec "playerctl play-pause") { locked = true; })
        (bindWithFlags ''"XF86AudioPrev"'' (exec "playerctl previous") { locked = true; })
      ];
      window_rule = [
        {
          name = "fix-xwayland-drags";
          match = {
            class = "^$";
            title = "^$";
            xwayland = true;
            float = true;
            fullscreen = false;
            pin = false;
          };
          no_focus = true;
        }
        {
          name = "zen-workspace";
          match.class = "zen-beta";
          workspace = lua "zenWorkspace";
        }
        {
          name = "code-workspace";
          match.class = "code";
          workspace = lua "codeWorkspace";
        }
        {
          name = "code-group";
          match.class = "code";
          group = "set";
        }
        {
          name = "picture-in-picture-floating";
          match.title = "Picture-in-Picture";
          float = true;
          pin = true;
          size = "30% 30%";
        }
      ];
    };
    importantPrefixes = [
      "config"
      "curve"
      "animation"
      "device"
      "env"
      "gesture"
      "monitor"
      "bind"
      "window_rule"
      "on"
    ];
  };
}
